In [80]:
import numpy as np

## 3D array

In [15]:
array_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
array_1.shape  ## 2 matrices , 2rows , 2columns

(2, 2, 2)

In [23]:
 array_1.ndim

3

In [24]:
array_1.size

8

In [81]:
array_1.dtype

dtype('int32')

## Zeros

In [82]:
zeros_array = np.zeros((2, 3, 4))  # 2 matrices, 3 rows, 4 columns
zeros_array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Ones

In [83]:
ones_array = np.ones((2, 3, 4))
ones_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## Full

In [45]:
full_array = np.full((2, 3, 4), 5)  # All elements are 5
full_array

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

## Random

In [46]:
random_array = np.random.rand(2, 3, 4)
random_array

array([[[0.51720451, 0.9972365 , 0.37294797, 0.38965741],
        [0.51045541, 0.99295797, 0.05181646, 0.05034831],
        [0.0945286 , 0.11387226, 0.93939039, 0.32438902]],

       [[0.82312637, 0.6307853 , 0.00282329, 0.60942696],
        [0.09793571, 0.93538918, 0.80309542, 0.1803842 ],
        [0.29135546, 0.64608402, 0.15144289, 0.0136578 ]]])

## Slicing

In [30]:
sample_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
sample_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
sample_array[0,1,1]

4

In [32]:
sample_array[0]

array([[1, 2],
       [3, 4]])

In [34]:
sample_array[:,0]

array([[1, 2],
       [5, 6]])

In [47]:
sample_array[:,:,0]

array([[1, 3],
       [5, 7]])

## Reshape

In [48]:
reshaped_array = array_1.reshape(8)  
reshaped_array

array([1, 2, 3, 4, 5, 6, 7, 8])

## Transpose

In [78]:
transposed_array = np.transpose(array_1, (1, 0, 2))
transposed_array

array([[[1, 2],
        [0, 0]],

       [[3, 4],
        [0, 0]]])

In [79]:
transposed_array.shape

(2, 2, 2)

## Mathematical Operations

In [39]:
array_A = np.full((2, 2, 2), 2)
array_A

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [40]:
array_B = np.full((2, 2, 2), 3)
array_B

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [43]:
array_A + array_B

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [53]:
array_A * array_B

array([[[6, 6],
        [6, 6]],

       [[6, 6],
        [6, 6]]])

In [55]:
array_A / array_B

array([[[0.66666667, 0.66666667],
        [0.66666667, 0.66666667]],

       [[0.66666667, 0.66666667],
        [0.66666667, 0.66666667]]])

## Statistical operations

In [56]:
np.mean(array_A)

2.0

In [57]:
np.max(array_A)

2

In [58]:
np.sum(array_A)

16

## Broadcasting

In [61]:
array_1 * 2

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]]])

## Broadcasting with compatible arrays

In [76]:
array_2D = np.array([[1, 2], [3, 4]])
array_2D

array([[1, 2],
       [3, 4]])

In [77]:
array_1 + array_2D

array([[[2, 4],
        [6, 8]],

       [[1, 2],
        [3, 4]]])

## Stacking

In [64]:
stacked_array = np.stack([array_A, array_B])
stacked_array

array([[[[2, 2],
         [2, 2]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3]]]])

In [65]:
stacked_array.shape

(2, 2, 2, 2)

## Splitting

In [74]:
split_arrays = np.split(array_1, 2, axis=0)
split_arrays

[array([[[1, 2],
         [3, 4]]]),
 array([[[0, 0],
         [0, 0]]])]

In [75]:
[arr.shape for arr in split_arrays]

[(1, 2, 2), (1, 2, 2)]

## Dot product

In [67]:
dot_product = np.dot(array_1[0], array_1[1])
dot_product

array([[19, 22],
       [43, 50]])

In [68]:
dot_product.shape

(2, 2)

## Matrix multiplication

In [69]:
matmul_result = np.matmul(array_1[0], array_1[1])
matmul_result

array([[19, 22],
       [43, 50]])

In [70]:
matmul_result.shape

(2, 2)

## Create mask

In [71]:
mask = array_1 > 4
mask

array([[[False, False],
        [False, False]],

       [[ True,  True],
        [ True,  True]]])

In [72]:
array_1[mask]

array([5, 6, 7, 8])

## Replace values

In [73]:
array_1[array_1 > 4] = 0
array_1

array([[[1, 2],
        [3, 4]],

       [[0, 0],
        [0, 0]]])