# Numpy

## Array

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.ndim

1

In [6]:
arr2=np.array([[1,2,3,4,5],[9,10,12,32,54]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 9, 10, 12, 32, 54]])

In [7]:
arr2.size

10

In [8]:
arr2.shape

(2, 5)

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [11]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5=np.ones((3,3),dtype=int)
arr5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Mathematic operation

In [14]:
arr5=np.arange(1,21).reshape(4,5)
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
arr6=np.arange(21,41).reshape(4,5)
arr6

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [16]:
arr5+arr6

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [17]:
np.add(arr5,arr6)

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [18]:
np.subtract(arr5,arr6)

array([[-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20]])

In [19]:
np.divide(arr5,arr6)

array([[0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333],
       [0.35483871, 0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949, 0.5       ]])

In [20]:
np.multiply(arr5,arr6)

array([[ 21,  44,  69,  96, 125],
       [156, 189, 224, 261, 300],
       [341, 384, 429, 476, 525],
       [576, 629, 684, 741, 800]])

In [22]:
##arr5 @ arr6 ## multiplicating according to matrix

In [24]:
## arr5.dot(arr6) ## multiplicating according to matrix

In [25]:
arr2.argmax() # index value of maximum number

9

In [26]:
arr2.max()

54

In [27]:
arr2.max(axis=1) # max according to row wise

array([ 5, 54])

In [28]:
arr2.min(axis=0) # min according to column wise

array([1, 2, 3, 4, 5])

In [29]:
np.mean(arr2)

13.2

In [30]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [3.        , 3.16227766, 3.46410162, 5.65685425, 7.34846923]])

In [31]:
np.std(arr2) # standard division

16.054905792311583

In [32]:
np.exp(arr2) # exponent

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [8.10308393e+03, 2.20264658e+04, 1.62754791e+05, 7.89629602e+13,
        2.83075330e+23]])