# Numpy

##  Array

In [2]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.ndim

1

In [7]:
arr2=np.array([[1,2,3,4,5],[9,10,12,32,54]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 9, 10, 12, 32, 54]])

In [8]:
arr2.size

10

In [9]:
arr2.shape

(2, 5)

In [10]:
arr2.dtype

dtype('int32')

In [13]:
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [15]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr5=np.ones((3,3),dtype=int)
arr5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
arr2.argmax() # index value of maximum number

9

In [22]:
arr2.max()

54

In [24]:
arr2.max(axis=1) # max according to row wise

array([ 5, 54])

In [25]:
arr2.min(axis=0) # min according to column wise

array([1, 2, 3, 4, 5])

In [26]:
np.mean(arr2)

13.2

In [27]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [3.        , 3.16227766, 3.46410162, 5.65685425, 7.34846923]])

In [28]:
np.std(arr2) # standard division

16.054905792311583

In [30]:
np.exp(arr2) # exponent

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [8.10308393e+03, 2.20264658e+04, 1.62754791e+05, 7.89629602e+13,
        2.83075330e+23]])